#!/usr/bin/env ruby
require './lib/versioner.rb'
require 'optparse'

options = {
  bump: false
}

parser = OptionParser.new do |opts|
  opts.banner = <<DOC
  Usage: ruby bump_version [options]
DOC

  opts.on('[TYPE]', '[TYPE]', [:patch, :minor, :major],
        "Bump version,
        [TYPE]: patch, minor, major - patch is default
        - patch - change last number, e.g. 1.2.3 -> 1.2.4
        - minor - change middle number, e.g. 1.2.3 -> 1.3.0
        - major - change first number, e.g. 1.2.3 -> 2.0.0") do |type|
    options[:bump] = type || :patch
  end

  opts.on_tail('-h', '--help', "Prints this help.") do
    puts opts
    exit
  end
end

options[:bump] = parser.parse(ARGV).first.to_sym
Versioner.call(options)
