version: "3"
services:
  db:
    image: 'postgres:11.3'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5430:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass redispassword
    ports:
      - '6380:6379'
    volumes:
      - 'redis:/data'
  web:
    depends_on:
      - 'db'
      - 'redis'
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - 'web:/application'
    environment:
      RAILS_ENV: ${RAILS_ENV}
      RAILS_SERVE_STATIC_FILES: ${RAILS_SERVE_STATIC_FILES}
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
    ports:
      - '3000:3000'

volumes:
  redis:
  db:
  web:
